-- 테이블 간의 관계 연관(R) 만들기
DROP TABLE DEPT_FK;
CREATE TABLE DEPT_FK(
    DEPTNO      NUMBER(2) PRIMARY KEY,
    DNAME       VARCHAR2(14),
    LOC         VARCHAR2(13)
);
SELECT * FROM DEPT_FK;

INSERT INTO DEPT_FK
VALUES (10, '개발1팀', '안동');

DELETE FROM DEPT_FK WHERE DEPTNO = 10;

DROP TABLE EMP_FK;
CREATE TABLE EMP_FK(
    EMPNO       NUMBER(4) PRIMARY KEY,
    ENAME       VARCHAR2(10),
    DEPTNO      NUMBER(2) REFERENCES DEPT_FK(DEPTNO) ON DELETE CASCADE
);
SELECT * FROM EMP_FK;
INSERT INTO EMP_FK
VALUES ( 3, '이순신', 10);

DELETE FROM EMP_FK WHERE DEPTNO = 10;
