-- MOVIES 테이블 생성
CREATE TABLE MOVIES (
    MOVIE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    GENRE VARCHAR2(50),
    RELEASE_DATE DATE,
    DIRECTOR VARCHAR2(50),
    RUNTIME NUMBER
);

-- ACTORS 테이블 생성
CREATE TABLE ACTORS (
    ACTOR_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    BIRTHDATE DATE,
    NATIONALITY VARCHAR2(50)
);

-- MOVIE_ACTORS 테이블 생성 (관계 제약 없음)
CREATE TABLE MOVIE_ACTORS (
    MOVIE_ID NUMBER,
    ACTOR_ID NUMBER
);



-- MOVIES 데이터 삽입
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (1, '기생충', '드라마', TO_DATE('2019-05-30', 'YYYY-MM-DD'), '봉준호', 132);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (2, '아가씨', '드라마', TO_DATE('2016-06-01', 'YYYY-MM-DD'), '박찬욱', 145);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (3, '신과함께', '판타지', TO_DATE('2017-12-20', 'YYYY-MM-DD'), '김용화', 139);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (4, '베테랑', '액션', TO_DATE('2015-08-05', 'YYYY-MM-DD'), '류승완', 124);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (5, '도둑들', '범죄', TO_DATE('2012-07-25', 'YYYY-MM-DD'), '최동훈', 135);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (6, '부산행', '액션', TO_DATE('2016-07-20', 'YYYY-MM-DD'), '연상호', 118);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (7, '암살', '드라마', TO_DATE('2015-07-22', 'YYYY-MM-DD'), '최동훈', 140);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (8, '광해', '드라마', TO_DATE('2012-09-13', 'YYYY-MM-DD'), '추창민', 131);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (9, '국제시장', '드라마', TO_DATE('2014-12-17', 'YYYY-MM-DD'), '윤제균', 126);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (10, '명량', '역사', TO_DATE('2014-07-30', 'YYYY-MM-DD'), '김한민', 128);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (11, '태극기 휘날리며', '전쟁', TO_DATE('2004-02-05', 'YYYY-MM-DD'), '강제규', 148);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (12, '사도', '역사', TO_DATE('2015-09-16', 'YYYY-MM-DD'), '이준익', 125);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (13, '밀정', '스릴러', TO_DATE('2016-09-07', 'YYYY-MM-DD'), '김지운', 140);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (14, '검사외전', '코미디', TO_DATE('2016-02-03', 'YYYY-MM-DD'), '이일형', 126);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (15, '변호인', '드라마', TO_DATE('2013-12-18', 'YYYY-MM-DD'), '양우석', 127);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (16, '관상', '드라마', TO_DATE('2013-09-11', 'YYYY-MM-DD'), '한재림', 139);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (17, '수상한 그녀', '코미디', TO_DATE('2014-01-22', 'YYYY-MM-DD'), '황동혁', 124);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (18, '터널', '스릴러', TO_DATE('2016-08-10', 'YYYY-MM-DD'), '김성훈', 126);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (19, '군도: 민란의 시대', '액션', TO_DATE('2014-07-23', 'YYYY-MM-DD'), '윤종빈', 137);
INSERT INTO MOVIES (MOVIE_ID, TITLE, GENRE, RELEASE_DATE, DIRECTOR, RUNTIME) VALUES (20, '럭키', '코미디', TO_DATE('2016-10-13', 'YYYY-MM-DD'), '이계벽', 112);

-- ACTORS 데이터 삽입
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (1, '송강호', TO_DATE('1967-01-17', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (2, '이정재', TO_DATE('1972-03-15', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (3, '하정우', TO_DATE('1978-03-11', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (4, '김태리', TO_DATE('1990-04-24', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (5, '전지현', TO_DATE('1981-10-30', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (6, '황정민', TO_DATE('1970-09-01', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (7, '마동석', TO_DATE('1971-03-01', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (8, '김수현', TO_DATE('1988-02-16', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (9, '유아인', TO_DATE('1986-10-06', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (10, '강동원', TO_DATE('1981-01-18', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (11, '조진웅', TO_DATE('1976-03-03', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (12, '한석규', TO_DATE('1964-11-03', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (13, '설경구', TO_DATE('1968-05-01', 'YYYY-MM-DD'), '한국');
INSERT INTO ACTORS (ACTOR_ID, NAME, BIRTHDATE, NATIONALITY) VALUES (14, '손예진', TO_DATE('
